{{- if not .remote }}
[".local/bin/devpod"]
type = "file"
executable = true
url = "https://github.com/loft-sh/devpod/releases/download/v0.7.0-alpha.34/devpod-{{.chezmoi.os}}-{{.chezmoi.arch}}"
{{- end }}

